### ISSUE TITLE
Evaluate cage extensions with verification criteria (focused on spoke feature variations)

### ISSUE THREAD

**Issue by ese8** [Duke-BME-Design/BME590L-Endoscopy#59]

**Comment by grossmhe** [comment]
Either Tuesday night (with everyone) or Wednesday (without Hannah) based on our access and availability to the scope

**Comment by souhaila30** [comment]
We started some verification testing, we realized that the parts don't fit because of the tabs. We have made changes to the designs. Further testing is pending until we update the designs.

**Comment by ese8** [comment]
Inability to access printed parts on the MEMs printer, waiting on arrival for latches/ delayed completion of verification testing at the present; will be able to revisit later this week.
