### ISSUE TITLE
Incorporate finalized fastening mechanism into extensions

### ISSUE THREAD

**Issue by ese8** [Duke-BME-Design/BME590L-Endoscopy#76]

**Comment by souhaila30** [comment]
This would also include determining most suited filament for printing (flexible or other)

**Comment by grossmhe** [comment]
O-ring design will be finalized.
-create a bevel to allow for o-ring to slip over more easily
-break up the lip to allow for grip/space to pull it off
-create a groove for o-ring to sit in while on the attachment 

**the lip and groove approach will allow us to use a tighter o-ring and get a more "firm" (?) closure
