### ISSUE TITLE
MEDx Proposal Due Feb 22nd

### ISSUE THREAD

**Issue by souhaila30** [Duke-BME-Design/BME590L-Endoscopy#78]

**Comment by ese8** [comment]
Budget:
Hannah- injection molding
Souhaila & Erin- 3D printing, other materials

**Comment by souhaila30** [comment]
Please review the proposal and comment in here. Once we all review it, I will go ahead and submit it. If you don't have time to review, please let me know. Let's aim to submit by Sunday.
