### ISSUE TITLE
Modify CAD design for Draw Latch

### ISSUE THREAD

**Issue by ese8** [Duke-BME-Design/BME590L-Endoscopy#82]

**Comment by grossmhe** [comment]
https://grabcad.com/library/draw-latch-3

**Comment by ese8** [comment]
Steve has been contacted about machining help, but at this point it won't be done before client testing on Monday. Back-up plan will be to try zip-ties.

**Comment by ese8** [comment]
Steve's feedback was to purchase instead of machine these parts. Parts are ordered and should arrive early/mid week. Will have to be evaluated to see if size is appropriate.
