### ISSUE TITLE
Continue work on optimization of clearance between extension and big dial

### ISSUE THREAD

**Issue by ese8** [Duke-BME-Design/BME590L-Endoscopy#92]

**Comment by ese8** [comment]
We talked about reducing tab size ever so slightly on our next modification to address this.

**Comment by ese8** [comment]
Are we putting this to rest- clearance was not an issue on the Pentax or Sim lab scopes, correct?

**Comment by grossmhe** [comment]
Yes-- putting it to rest, finally!
