### ISSUE TITLE
Start IP and IDF research and next steps

### ISSUE THREAD

**Issue by grossmhe** [Duke-BME-Design/BME590L-Endoscopy#95]

**Comment by grossmhe** [comment]
Robin Razer = director
**Eric Wagner = lawyer, usually pretty responsive 
Interns would be helpful to contact for work

**Comment by grossmhe** [comment]
Met with Robin and Bethany on 4/6

**Comment by souhaila30** [comment]
It was great! They will be sending us a form to fill out later today to kick-start the process. We are aiming to have a provisional patent submitted before the symposium. They will be doing some patent research to see what's out there. And over the next few weeks, we will set up a meeting with Eric Wagner, the patent attorney to provide him with all the information he needs. We are in good shape as far as having the documentation for filing the patent.
